### ISSUE TITLE
Fix broken link in README

### ISSUE THREAD

**Issue by lgs85** [nhs-r-community/intro_r_data#8]
A link in the README files ([this line](https://github.com/nhs-r-community/intro_r_data/blob/1e0e78c923c9063cc4026e3d217d345b7642318d/README.Rmd#L26)) is broken. I assume that this should direct to the following instead:

- [setup](https://nhsrway.nhsrcommunity.com/training.html)
- [materials](https://nhs-r-community.github.io/intro_r/)

**Comment by Lextuga007** [comment]
Nice spot! Yes, that's very out of date. Would you like to do a Pull Request to update the README?

**Comment by Lextuga007** [comment]
I tidied up the README so it links to the NHS-R Way book as that's an easier way to maintain the downloading information for several courses. Thanks for the issue, it's much appreciated 😄
